application: vennmeme
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: dist/index.html
  upload: dist/
- url: /(.+)
  static_files: dist/\1
  upload: dist/

builtins:
- remote_api: on
- deferred: on

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

instance_class: F1
automatic_scaling:
  min_pending_latency: 200ms
  max_pending_latency: 500ms
  min_idle_instances: 0
  max_idle_instances: 1
